<?php
return [
    'master_order' => ['employees', 'taxpayers', 'job-types', 'kpi-weights', 'incentive-settings', 'regions', 'periods'],
    'kpi_metrics' => [
        'target' => 'Target',
        'realisasi' => 'Realisasi',
        'penagihan_berhasil' => 'Penagihan Berhasil',
        'verval' => 'Verval',
        'gps_valid' => 'GPS Valid',
        'ketepatan_waktu' => 'Ketepatan Waktu',
        'kelengkapan_dokumen' => 'Kelengkapan Dokumen',
    ],
    'modules' => [
        'employees' => [
            'title' => 'Data Pegawai',
            'table' => 'employees',
            'list' => ['nip', 'name', 'username', 'position', 'region_id', 'role', 'status'],
            'fields' => [
                'nip' => ['label' => 'NIP', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama', 'type' => 'text', 'required' => true],
                'username' => ['label' => 'Username Login', 'type' => 'text', 'required' => true],
                'password_hash' => ['label' => 'Password', 'type' => 'password', 'required_on_create' => true],
                'position' => ['label' => 'Jabatan', 'type' => 'text', 'required' => true],
                'region_id' => ['label' => 'Wilayah', 'type' => 'select', 'source' => 'regions', 'source_label' => 'name'],
                'phone' => ['label' => 'Telepon', 'type' => 'text'],
                'role' => ['label' => 'Peran', 'type' => 'select', 'required' => true, 'options' => ['admin' => 'Admin', 'petugas' => 'Petugas']],
                'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['active' => 'Aktif', 'inactive' => 'Nonaktif'], 'default' => 'active'],
            ],
        ],
        'taxpayers' => [
            'title' => 'Data Wajib Pajak',
            'table' => 'taxpayers',
            'list' => ['tax_number', 'name', 'region_id', 'address', 'latitude', 'longitude', 'status'],
            'fields' => [
                'tax_number' => ['label' => 'NPWP / ID Pajak', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Wajib Pajak', 'type' => 'text', 'required' => true],
                'region_id' => ['label' => 'Wilayah', 'type' => 'select', 'required' => true, 'source' => 'regions', 'source_label' => 'name'],
                'address' => ['label' => 'Alamat', 'type' => 'textarea', 'required' => true],
                'latitude' => ['label' => 'Latitude Lokasi', 'type' => 'number', 'step' => '0.0000001'],
                'longitude' => ['label' => 'Longitude Lokasi', 'type' => 'number', 'step' => '0.0000001'],
                'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['active' => 'Aktif', 'inactive' => 'Nonaktif'], 'default' => 'active'],
            ],
        ],
        'job-types' => [
            'title' => 'Jenis Pekerjaan',
            'table' => 'job_types',
            'list' => ['name', 'description', 'default_target', 'status'],
            'fields' => [
                'name' => ['label' => 'Nama Jenis Pekerjaan', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Deskripsi', 'type' => 'textarea'],
                'default_target' => ['label' => 'Target Default', 'type' => 'number', 'step' => '1', 'default' => 1],
                'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['active' => 'Aktif', 'inactive' => 'Nonaktif'], 'default' => 'active'],
            ],
        ],
        'kpi-weights' => [
            'title' => 'Bobot KPI',
            'table' => 'kpi_weights',
            'list' => ['metric_key', 'metric_name', 'weight_percent'],
            'fields' => [
                'metric_key' => ['label' => 'Kode Metrik', 'type' => 'select', 'required' => true, 'options' => [
                    'target' => 'Target',
                    'realisasi' => 'Realisasi',
                    'penagihan_berhasil' => 'Penagihan Berhasil',
                    'verval' => 'Verval',
                    'gps_valid' => 'GPS Valid',
                    'ketepatan_waktu' => 'Ketepatan Waktu',
                    'kelengkapan_dokumen' => 'Kelengkapan Dokumen',
                ]],
                'metric_name' => ['label' => 'Nama Metrik', 'type' => 'text', 'required' => true],
                'weight_percent' => ['label' => 'Bobot (%)', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ],
        ],
        'incentive-settings' => [
            'title' => 'Setting Insentif',
            'table' => 'incentive_settings',
            'list' => ['name', 'minimum_kpi', 'bonus_multiplier', 'status'],
            'fields' => [
                'name' => ['label' => 'Nama Setting', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Deskripsi', 'type' => 'textarea'],
                'minimum_kpi' => ['label' => 'Minimum KPI', 'type' => 'number', 'step' => '0.01', 'default' => 0],
                'bonus_multiplier' => ['label' => 'Multiplier', 'type' => 'number', 'step' => '0.01', 'default' => 1],
                'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['active' => 'Aktif', 'inactive' => 'Nonaktif'], 'default' => 'active'],
            ],
        ],
        'regions' => [
            'title' => 'Wilayah',
            'table' => 'regions',
            'list' => ['code', 'name', 'center_latitude', 'center_longitude', 'radius_meters'],
            'fields' => [
                'code' => ['label' => 'Kode Wilayah', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Wilayah', 'type' => 'text', 'required' => true],
                'center_latitude' => ['label' => 'Latitude Pusat', 'type' => 'number', 'step' => '0.0000001'],
                'center_longitude' => ['label' => 'Longitude Pusat', 'type' => 'number', 'step' => '0.0000001'],
                'radius_meters' => ['label' => 'Radius Validasi (meter)', 'type' => 'number', 'step' => '1', 'default' => 500],
            ],
        ],
        'periods' => [
            'title' => 'Target Periode',
            'table' => 'periods',
            'list' => ['code', 'name', 'start_date', 'end_date', 'status'],
            'fields' => [
                'code' => ['label' => 'Kode Periode', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Periode', 'type' => 'text', 'required' => true],
                'start_date' => ['label' => 'Tanggal Mulai', 'type' => 'date', 'required' => true],
                'end_date' => ['label' => 'Tanggal Selesai', 'type' => 'date', 'required' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['open' => 'Open', 'closed' => 'Closed'], 'default' => 'open'],
            ],
        ],
    ],
];
